language: python
install: echo "Install test dependencies"
script: echo "Run tests"
python: "3.6"
before_deploy:
  - pip install kodi-addon-checker
  - pip install git+https://github.com/romanvm/kodi-addon-submitter.git
  - submit-addon -z plugin.video.rtpplay # Create an installable ZIP
  - export RELEASE_ZIP=$(ls *.zip)
addon_check:
  - provider: script
    script: kodi-addon-checker --branch=krypton .
    on:
      tags: false
deploy:
  # Publish an installable ZIP to GitHub Releases
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: $RELEASE_ZIP
    skip_cleanup: true
    on:
      tags: true
  # Submit to the official Kodi repository
  - provider: script
    script: submit-addon -r repo-plugins -b krypton --pull-request plugin.video.rtpplay
    on:
      tags: true
notifications:
  email: true